# This is a basic workflow to help you get started with Actions

name: Sync Images

on:
  workflow_dispatch:
    inputs:
      src_image:
        description: 'Origin image'
        required: true
      dst_image_tag:
        description: 'Destination image tag'
        required: true
      dst_image_registry:
        description: 'Destination image registry'
        required: false
        default: 'registry.cn-beijing.aliyuncs.com'
      dst_image_name:
        description: 'Destination image namespace'
        required: false
        default: 'wa/hub'
      dst_image_tag:
        description: 'Destination image tag'
        required: true
      dst_registry_username:
        description: 'Destination image registry username'
        required: true
        default: '${{ secrets.DST_REGISTRY_USERNAME }}'
      dst_registry_password:
        description: 'Destination image registry password'
        required: true
        default: '${{ secrets.DST_REGISTRY_PASSWORD }}'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        uses: docker/login-action@v3.3.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ${{ github.event.inputs.dst_registry }}
          # Username used to log against the Docker registry
          username: ${{ github.event.inputs.dst_registry_username }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ github.event.inputs.dst_registry_password }}

      - name: Sync Images
        run: |
          set -e
          docker pull ${{ github.event.inputs.src_image }}
          docker tag ${{ github.event.inputs.src_image }} ${{ github.event.inputs.dst_image_registry }}/${{ github.event.inputs.dst_image_name }}:${{ github.event.inputs.dst_image_tag }}
          docker push ${{ github.event.inputs.dst_image_registry }}/${{ github.event.inputs.dst_image_name }}:${{ github.event.inputs.dst_image_tag }}
                
